version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    depends_on:
      - db
      - redis
      - elasticsearch
    ports:
      - "8080:80"

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "test@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1401:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  mssql-data:
    driver: local
  esdata:
    driver: local
